db:
  settings:
    0:
      url: jdbc:postgresql://localhost:5433/aion_0
      username: postgres
      driver: org.postgresql.Driver
      password: password
    1:
      url: jdbc:postgresql://localhost:5433/aion_1
      username: postgres
      driver: org.postgresql.Driver
      password: password
  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/changelog.xml
server:
  port: 8081